# 开发环境配置
server:
  # 服务端口
  port: 80
  servlet:
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 250
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 20

# Spring 配置
spring:
  # datasource
  profiles:
    active: druid
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
      additional-paths: src/main/java
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.scauxg.restaurant
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mappers/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis-config.xml